export const tableUIHelper = {
  columns: {
    width: {
      date: "180px",
      loan: "110px",
      phone: "140px",
      fee: "110px",
      amount: "150px",
      description: "240px",
    },
  },
};

export const monthsOfYear = [
  "",
  "Enero",
  "Febrero",
  "Marzo",
  "Abril",
  "Mayo",
  "Junio",
  "Julio",
  "Agosto",
  "Septiembre",
  "Octubre",
  "Noviembre",
  "Diciembre",
];

export const moduleNames = [
  ["ACCOUNTING_CLOSING", "Cierre contable"],
  ["ACCOUNT_CATALOGS", "Catálogo de cuentas"],
  ["ACCOUNT_OPERATION", "Operaciones contables"],
  ["ACCOUNT_PAYABLE", "Cuentas por pagar"],
  ["ALERT", "name"],
  ["BANKS", "name"],
  ["BANKS_ACCOUNT_CHECKS", "name"],
  ["BANKS_ACCOUNTS", "name"],
  ["BANKS_ENTRY", "name"],
  ["BANKS_RETIREMENTS", "name"],
  ["CALL_CENTER", "name"],
  ["CANDIDATES_RECRUITMENT", "name"],
  ["CHARGES", "name"],
  ["CHECK_PAYMENTS", "name"],
  ["CHECK_PAYMENTS_VALIDATE", "name"],
  ["COMPANY", "name"],
  ["CUSTOMERS", "Clientes"],
  ["CUSTOMER_TYPES", "name"],
  ["DASHBOARD_BILLING", "name"],
  ["DASHBOARD_LOAN", "Dashboard de préstamos"],
  ["DASHBOARD_LOAN_APPLICATION", "Dashboard de solicitudes"],
  ["DEPARTMENTS", "name"],
  ["DETERMINATION_ACCOUNTS", "name"],
  ["DOCUMENT_TYPES", "name"],
  ["EMPLOYEES", "Empleados"],
  ["EVALUATIONS", "name"],
  ["EVALUATION_TYPES", "name"],
  ["EXPENSES_TYPES", "name"],
  ["GENERAL_DIARIES", "name"],
  ["INTEREST_RATES", "name"],
  ["LATE_PAYMENTS", "name"],
  ["LOAN_APPLICATIONS", "Solicitudes de préstamo"],
  ["LOAN_EMPLOYEE", "name"],
  ["LOAN_EMPLOYEE_APPLICATIONS", "name"],
  ["LOANS", "Préstamos"],
  ["METHOD_PAYMENTS", "name"],
  ["MINOR_EXPENSES", "Gastos menores"],
  ["MUNICIPALITY", "name"],
  ["NCF", "name"],
  ["OTHER_REPORT", "name"],
  ["PAYMENT", "Cobros"],
  ["PAYMENT_CONTROL", "Control de cobros"],
  ["PAYMENT_ROUTER", "name"],
  ["PAYROLL_GROUPS", "name"],
  ["PAYROLL_PARAMETERS", "name"],
  ["PAYROLLS", "Nomina"],
  ["POSITIONS", "name"],
  ["POSITIONS_RECRUITMENT", "name"],
  ["PROVINCE", "name"],
  ["REGISTER_CLOSE", "Cierre de caja"],
  ["REPORT_ACCOUNT_PAYABLE", "Reporte de cuentas por pagar"],
  ["REPORT_CHARGES", "Reporte de gastos"],
  ["REPORT_CHECKING_BALANCE", "Reporte de balance de comprobación"],
  ["REPORT_COMMISSION", "Reporte de comisiones"],
  ["REPORT_CREDIT_DATA", "Reporte de datacrédito"],
  ["REPORT_CUSTOMER_LOAN", "Reporte de préstamos a empleados"],
  ["REPORT_DETAIL_LOAN", "Reporte de detalle de préstamos"],
  ["REPORT_LOAN", "Reporte de préstamos"],
  ["REPORT_PAYMENTS", "Reporte de cobros"],
  ["REPORT_RECEIVABLE", "name"],
  ["REPORT_RECONCILIATIONS", "name"],
  ["REPORT_REGISTER_CLOSE", "Reporte de cierre de caja"],
  ["ROL", "name"],
  ["SCALE_DISCOUNT_INCOME_TAXES", "name"],
  ["SECTION", "name"],
  ["SETTING_REFINANCE", "name"],
  ["SETTINGS", "name"],
  ["STAFF_ACTIONS", "name"],
  ["STAFF_PENDING_APPROVAL", "name"],
  ["SUPERVISOR", "name"],
  ["TYPE_OF_STAFF_ACTIONS", "name"],
  ["USERS", "name"],
  ["ZONE", "name"],
];
